http-port: 80 # http重定向https配置

server:
  port: 8888
  ssl:
    key-store: classpath:gaoyubo.cn.jks
    key-store-password: z14vf71x6j4xb6g
    key-store-type: JKS
    enabled: true

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml

spring:
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  redis:
    host: 127.0.0.1  # IP
    port: 6379  # 端口号
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数
        max-wait: -1ms  # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 0 # 连接池中的最小空闲连接
        max-idle: 8 # 连接池中的最大空闲连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/securefiletransfer?useUnicode=true&useSSL=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: gyb20010204
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      stat-view-servlet:
        login-password: admin
        login-username: admin
        enabled: true
      #配置监控统计拦截的filters,去掉后监控界面sql将无法统计
      filters: stat

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
